# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: État social et solidarités
author: Manon Pesle
email: manon.pesle@umrpacte.fr
license: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
description: > # this means to ignore newlines until "baseurl:"
  Site de la conférence de méthodes "Etat social et solidarités", 3e année SRI, groupes 1 et 3.
baseurl: "/etatsocial" # the subpath of your site, e.g. /blog
url: "https://mpesle.github.io" # the base hostname & protocol for your site
future: true
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
